kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.certSecretName }}
  namespace: {{ .Values.namespace }}
data:
  tls.crt: {{ .Files.Get "certs/simulated-server.workload.svc.crt" | b64enc }}
  tls.key: {{ .Files.Get "certs/simulated-server.workload.svc.key" | b64enc }}
  ca.crt: {{ .Files.Get "certs/rootCA.crt" | b64enc }}
type: kubernetes.io/tls
