{
 "title": "Nodes Monitoring",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "WorkerGroup",
    "query": {
     "query": "label_values(kube_node_created,label_worker_garden_sapcloud_io_group)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_created{label_worker_garden_sapcloud_io_group=~\"$WorkerGroup\"}, node)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(node_memory_SwapTotal_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Total Nodes Count in $WorkerGroup Worker",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Current Healthy Nodes Count in $WorkerGroup Worker",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_node_status_condition{condition=\"Ready\", status=\"true\",node=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Average Nodes Liveness Time in Hours",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(max(time() - kube_node_created{node=~\"^$Node$\"}) by (node)) / 3600"
    }
   ]
  },
  {
   "title": "Total Nodes Count in $WorkerGroup Worker in Range ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(kube_node_info{node=~\"^$Node$\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Unhealthy Nodes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(changes(kube_node_status_condition{status=\"false\",condition!=\"Ready\", node=~\"^$Node$\"}[15m]) > 0) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Number of Nodes Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(kube_node_info{node=~\"^$Node$\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes Liveness",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(time() - kube_node_created{node=~\"^$Node$\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes Liveness Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(max(time() - kube_node_created{node=~\"^$Node$\"}) by (node))",
     "legendFormat": "average"
    }
   ]
  },
  { "title": "Nodes CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Nodes CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",node=~\"^$Node$\"}[1m])) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes RAM memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes SWAP usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$Instance\"}) by (instance) - sum(node_memory_SwapFree_bytes{instance=~\"$Instance\"}) by (instance)",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Nodes filesystem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "{{ node }}"
    }
   ]
  }
 ]
}