{
 "title": "Pods Monitoring",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "WorkerGroup",
    "query": "label_values(kube_node_created,label_worker_garden_sapcloud_io_group)"
   },
   {
    "name": "Node",
    "query": "label_values(kube_node_created{label_worker_garden_sapcloud_io_group=\"$WorkerGroup\"}, node)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{node=~\"^$Node$\",pod!~\".*-deployment-.*\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "Pods status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{pod=~\"^$Pod$\"} == 1 ) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pending/Failed/Unknown Pods",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(kube_pod_status_phase{pod=~\"^$Pod$\",phase=~\"Pending|Failed|Unknown\"} == 1) * on (pod) group_left(node) kube_pod_info"
    }
   ]
  },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\" , image!=\"\",pod=~\"^$Pod$\"}[1m])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\", container!=\"POD\" , image!=\"\",pod=~\"^$Pod$\"}) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}